sudo: required
branches:
  only:
    - master
services:
  - docker
language: go
go:
 - "1.10.x"
env:
  global:
    - TEAMCITY_ADDR=http://localhost:8112
    - TF_ACC=1
    - TEAMCITY_USER=admin
    - TEAMCITY_PASSWORD=admin

script:
  # run acceptance tests
 - ./integration_tests/start_teamcity.sh  # start and wait for TeamCity
 - go test -v -timeout 180s ./...
