name: Publish binaries on release
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/builder
  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dump gitconfig
        run: |
          cat ./.git/config
      - name: github-upload-release
        uses: docker://moonswitch/github-upload-release:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: not actor nektos/act

